version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employees
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    working_dir: /app
    command: ["java", "-cp", ".:mysql-connector-java-8.0.33.jar", "EmployeeManagementSystem"]
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/employees?useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: root
      DB_PASSWORD: password
    volumes:
      - ./csv:/app  # Mount for CSV export access

volumes:
  mysql-data:
